apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: {{ template "datapower-operator.namespacedname" . }}
  labels:
    app.kubernetes.io/instance: {{ template "datapower-operator.namespacedname" . }}
    app.kubernetes.io/name: {{ template "datapower-operator.namespacedname" . }}
    app.kubernetes.io/managed-by: datapower-operator
rules:

# meeded for administration of validating and defaulting webhooks
# for the CRDs which this operator manages
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

# needed for reconciliation of the admission controllers
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  verbs:
  - get
  - list

# needed for management of owned CRDs
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - update

# needed for management of conversion webhook deployment, which can
# exist in other namespaces than this operator
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - list

# needed for management of conversion webhook deployment, which can
# exist in other namespaces than this operator
- apiGroups:
  - ""
  resources:
  - services
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

# needed for management of conversion webhook deployment, which can
# exist in other namespaces than this operator
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

# Needed for conversion webhook across namespaces
- apiGroups:
  - datapower.ibm.com
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

# Needed for OCP platform checks
- apiGroups:
  - config.openshift.io
  resources:
  - clusterversions
  verbs:
  - get

{{- if eq .Values.operator.installMode "AllNamespaces" }}
# If installMode is AllNamespaces, we should use the cluster role for everything.
{{ $.Files.Get "static/role_rules.yaml" }}
{{- end }}
