apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: {{ template "datapower-operator.namespacedname" . }}
  labels:
    app.kubernetes.io/instance: {{ template "datapower-operator.namespacedname" . }}
    app.kubernetes.io/name: {{ template "datapower-operator.namespacedname" . }}
    app.kubernetes.io/managed-by: datapower-operator
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  - pods/log
  verbs:
  - get
  - list
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
- apiGroups:
  - apiextensions.k8s.io
  resourceNames:
  - datapowerservices.datapower.ibm.com
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - apps
  resourceNames:
  - datapower-operator-conversion-webhook
  resources:
  - deployments
  verbs:
  - delete
  - patch
  - update
- apiGroups:
  - config.openshift.io
  resources:
  - clusterversions
  verbs:
  - get
- apiGroups:
  - datapower.ibm.com
  resources:
  - datapowermonitors
  - datapowermustgathermanagers
  - datapowermustgathers
  - datapowerrollouts
  - datapowerservicebindings
  - datapowerservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - datapower.ibm.com
  resources:
  - datapowermonitors/status
  - datapowermustgathermanagers/status
  - datapowermustgathers/status
  - datapowerrollouts/status
  - datapowerservicebindings/status
  - datapowerservices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - datapower.ibm.com
  resources:
  - datapowermustgathermanagers/finalizers
  - datapowermustgathers/finalizers
  verbs:
  - update
- apiGroups:
  - operators.coreos.com
  resources:
  - clusterserviceversions
  verbs:
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  verbs:
  - create
  - get
  - list
- apiGroups:
  - rbac.authorization.k8s.io
  resourceNames:
  - dpop-conv-webhook
  resources:
  - clusterrolebindings
  - clusterroles
  verbs:
  - update
- apiGroups:
  - security.openshift.io
  resourceNames:
  - datapower-root
  resources:
  - securitycontextconstraints
  verbs:
  - use

{{- if eq .Values.operator.installMode "AllNamespaces" }}
# If installMode is AllNamespaces, we should use the cluster role for everything.
{{ $.Files.Get "static/role_rules.yaml" }}
{{- end }}
