apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: {{ template "datapower-operator.namespacedname" . }}
  labels:
    app.kubernetes.io/instance: {{ template "datapower-operator.namespacedname" . }}
    app.kubernetes.io/name: {{ template "datapower-operator.namespacedname" . }}
    app.kubernetes.io/managed-by: datapower-operator
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - update
  - watch
  - patch
  - list
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - datapower-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  verbs:
  - get
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
  - monitoringcontroller.cloud.ibm.com
  resources:
  - monitoringdashboards
  verbs:
    - create
    - get
    - list
    - watch
- apiGroups:
  - cp4i.ibm.com
  resources:
  - cp4iservicesbindings
  verbs:
  - create
  - get
  - list
  - watch
  - patch
  - update
  - delete
