apiVersion: v1
kind: ServiceAccount
metadata:
  name: datapower-operator
  labels:
    app.kubernetes.io/instance: datapower-operator
    app.kubernetes.io/name: datapower-operator
    app.kubernetes.io/managed-by: datapower-operator
{{- if .Values.operator.imagePullSecrets }}
imagePullSecrets:
{{- range .Values.operator.imagePullSecrets }}
- name: {{ .name }}
{{- end }}
{{- end }}
